export interface TemplateMetadata {
  id: string;
  name: string;
  description: string;
  category: 'Clean' | 'Developer' | 'Bold' | 'Creative' | 'Professional' | 'Academic';
  accentColor: string;
  tags: string[];
  features: string[];
  previewBg: string;
}

export const TEMPLATES_REGISTRY: TemplateMetadata[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean modern dark layout with emerald accents and balanced spacing. Ideal for software engineers who value understated clarity.',
    category: 'Clean',
    accentColor: '#10b981',
    tags: ['Dark Mode', 'Modern', 'Clean', 'Fast'],
    features: ['Highlighted Projects', 'Timeline', 'Contact Form', 'Clean Typography'],
    previewBg: 'bg-zinc-950',
  },
  {
    id: 'noir',
    name: 'Noir',
    description: 'High-luxury black and gold monochrome typography. Sophisticated editorial aesthetic for elite technologists and design engineers.',
    category: 'Clean',
    accentColor: '#c5a059',
    tags: ['Luxury', 'Monochrome', 'Gold Accents', 'Serif'],
    features: ['Minimalist Luxury', 'Serif Headers', 'Discreet Badges', 'Case Studies'],
    previewBg: 'bg-[#0a0a0c]',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Retro hacker Unix CLI interface with monospace typography, command prompt outputs, and interactive tab filtering.',
    category: 'Developer',
    accentColor: '#2ea043',
    tags: ['CLI', 'Linux / Bash', 'Monospace', 'Hacker'],
    features: ['Command Syntax', 'Tab Filters', 'ASCII Banner', 'Git Commit Log'],
    previewBg: 'bg-[#0d1117]',
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'New York Times & Vogue-inspired broadsheet layout with drop caps, pull quotes, multi-column articles, and rich serif titles.',
    category: 'Professional',
    accentColor: '#1a1a1a',
    tags: ['Magazine', 'Newspaper', 'Serif', 'Multi-Column'],
    features: ['Drop Caps', 'Chronicle', 'Broadsheet Header', 'Pull Quotes'],
    previewBg: 'bg-[#faf8f5]',
  },
  {
    id: 'swiss',
    name: 'Swiss Style',
    description: 'International Typographic Style with asymmetric bold geometric grids, red accent blocks, and strict structural hierarchy.',
    category: 'Bold',
    accentColor: '#ff3b30',
    tags: ['Swiss Graphic', 'Heavy Helvetica', 'Red Accent', 'Grid System'],
    features: ['Numbered Sections', 'Asymmetric Layout', 'Bold Rules', 'Matrix'],
    previewBg: 'bg-[#f4f4f0]',
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    description: 'Neo-brutalism with 4px black borders, harsh drop shadows, high-voltage yellow & cyan accents, and raw sticker badges.',
    category: 'Bold',
    accentColor: '#ffdf00',
    tags: ['Neo-Brutalism', 'Hard Shadows', 'High Contrast', 'Sticker Badges'],
    features: ['Offset Shadows', 'Punchy Badges', 'Bold Borders', 'High Impact'],
    previewBg: 'bg-[#fffdf0]',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Luminous mesh gradients and deep celestial indigo atmosphere with iridescent glows and frosted glass cards.',
    category: 'Creative',
    accentColor: '#a855f7',
    tags: ['Mesh Gradient', 'Violet & Indigo', 'Iridescent', 'Glowing'],
    features: ['Ambient Orbs', 'Gradient Headings', 'Glassmorphism', 'Soft Shadows'],
    previewBg: 'bg-[#070714]',
  },
  {
    id: 'glass',
    name: 'Glassmorphism',
    description: 'Apple and visionOS inspired frosted acrylic panels with translucent reflections, cyan glows, and sleek pill elements.',
    category: 'Clean',
    accentColor: '#06b6d4',
    tags: ['Frosted Glass', 'Backdrop Blur', 'Apple Aesthetic', 'Clean'],
    features: ['Translucent Cards', 'Backdrop Blur', 'Subtle Borders', 'Reflective Glass'],
    previewBg: 'bg-[#0b0f19]',
  },
  {
    id: 'cyber',
    name: 'Cyberpunk',
    description: 'High-tech neon cyan and magenta HUD interface with telemetry logs, corner markings, and glitch badges.',
    category: 'Developer',
    accentColor: '#00f0ff',
    tags: ['Cyberpunk', 'Neon Cyan & Magenta', 'HUD Markings', 'Synthwave'],
    features: ['HUD Overlays', 'Status Brackets', 'System Telemetry', 'Monospace Code'],
    previewBg: 'bg-[#08090d]',
  },
  {
    id: 'studio',
    name: 'Studio',
    description: 'Creative agency portfolio layout with massive headline typography, warm coral accents, and full-bleed project cards.',
    category: 'Creative',
    accentColor: '#ff5533',
    tags: ['Agency', 'Coral Accent', 'Showcase Cards', 'Bold Display'],
    features: ['Full-Width Case Studies', 'Spacious Grid', 'Studio Ethos', 'Large Type'],
    previewBg: 'bg-[#111113]',
  },
  {
    id: 'academic',
    name: 'Academic CV',
    description: 'Formal university curriculum vitae and LaTeX paper layout. Ideal for scholars, PhD candidates, and research scientists.',
    category: 'Academic',
    accentColor: '#1d4ed8',
    tags: ['LaTeX Style', 'Curriculum Vitae', 'Paper', 'Publications'],
    features: ['Paper Margins', 'Numbered Publications', 'Citations', 'Formal Credentials'],
    previewBg: 'bg-[#fdfdfc]',
  },
  {
    id: 'research',
    name: 'Research Lab',
    description: 'Machine learning & systems research lab aesthetic with problem-solution-impact matrix and benchmark chips.',
    category: 'Academic',
    accentColor: '#14b8a6',
    tags: ['AI / ML', 'Benchmark Metrics', 'Evaluation Cards', 'Deep Teal'],
    features: ['Empirical Matrix', 'Hypothesis Cards', 'Technical Apparatus', 'Evaluation'],
    previewBg: 'bg-[#0b0f19]',
  },
  {
    id: 'engineer',
    name: 'Systems Engineer',
    description: 'Tailored for systems, cloud, and infrastructure architects. Emphasizes latency, throughput, and system topology.',
    category: 'Developer',
    accentColor: '#238636',
    tags: ['Cloud / DevOps', 'Infrastructure', 'Systems Architecture', 'Topology'],
    features: ['Cluster Badges', 'System Metrics', 'Topology Cards', 'Git Clones'],
    previewBg: 'bg-[#0d1117]',
  },
  {
    id: 'founder',
    name: 'Founder & Pitch',
    description: 'Startup pitch deck and founder portfolio highlighting elevator pitches, traction metrics, and venture track records.',
    category: 'Professional',
    accentColor: '#6366f1',
    tags: ['Startup Founder', 'Elevator Pitch', 'Traction', 'Venture Portfolio'],
    features: ['Venture Cards', 'Market Need Blocks', 'Traction Callouts', 'Investor CTAs'],
    previewBg: 'bg-[#090a0f]',
  },
  {
    id: 'freelancer',
    name: 'Freelance Pro',
    description: 'High-converting client portfolio with service cards, client guarantees, booking CTAs, and warm amber accents.',
    category: 'Professional',
    accentColor: '#f59e0b',
    tags: ['Freelancer', 'High Conversion', 'Client Services', 'Booking CTA'],
    features: ['Client Results', 'Guarantees', 'Direct Booking', 'Case Studies'],
    previewBg: 'bg-[#0a0d14]',
  },
  {
    id: 'creative',
    name: 'Creative Pastel',
    description: 'Playful pastel gradients with warm rose tones, rounded pill badges, and friendly expressive design energy.',
    category: 'Creative',
    accentColor: '#f43f5e',
    tags: ['Playful', 'Pastel Pink', 'Rounded Pills', 'Expressive'],
    features: ['Candy Badges', 'Soft Gradients', 'Friendly Persona', 'Interactive Pills'],
    previewBg: 'bg-[#faf8f5]',
  },
  {
    id: 'resume',
    name: 'Executive Resume',
    description: 'Classic 2-column executive resume format with sidebar skills and clean chronological work history.',
    category: 'Professional',
    accentColor: '#334155',
    tags: ['Corporate CV', '2-Column Resume', 'Executive', 'Structured'],
    features: ['Sidebar Credentials', 'Chronology', 'Clean Summary', 'Print Ready'],
    previewBg: 'bg-[#edeef0]',
  },
  {
    id: 'student',
    name: 'Campus / Junior',
    description: 'Vibrant college campus and junior developer portfolio highlighting university coursework, hackathon wins, and GitHub builds.',
    category: 'Developer',
    accentColor: '#0ea5e9',
    tags: ['Student', 'Hackathons', 'Junior Dev', 'Campus Spirit'],
    features: ['Hackathon Wins', 'University Banner', 'Learning Projects', 'Club Leadership'],
    previewBg: 'bg-[#0e131f]',
  },
  {
    id: 'monochrome',
    name: 'Pure Monochrome',
    description: 'Stark, pure black & white without any color saturation. High-contrast typography and uncompromising minimalist focus.',
    category: 'Clean',
    accentColor: '#ffffff',
    tags: ['Zero Saturation', 'Pure Black & White', 'Stark Minimalist', 'High Contrast'],
    features: ['Pure Grayscale', 'Numbered Statement', 'Linear Grid', 'Clean Contrast'],
    previewBg: 'bg-black',
  },
  {
    id: 'experimental',
    name: 'Experimental Split',
    description: 'Interactive split-screen layout with sticky left identity panel, scrollable right content feed, and amber micro-interactions.',
    category: 'Bold',
    accentColor: '#fbbf24',
    tags: ['Split Screen', 'Sticky Panel', 'Feed Layout', 'Interactive'],
    features: ['Dual Column', 'Sticky Identity', 'Continuous Feed', 'Micro Badges'],
    previewBg: 'bg-[#0e0e11]',
  },
];

export function getTemplateById(id: string): TemplateMetadata {
  const found = TEMPLATES_REGISTRY.find((t) => t.id.toLowerCase() === id.toLowerCase());
  return found || TEMPLATES_REGISTRY[0]; // fallback to minimal
}

export function getAllTemplates(): TemplateMetadata[] {
  return TEMPLATES_REGISTRY;
}
